# Generated by Django 5.0.6 on 2024-08-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='manytomanyapp.student'),
        ),
    ]
