# Generated by Django 5.0.6 on 2024-08-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyapp', '0002_course_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
