# Generated by Django 5.0.6 on 2024-08-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
