# Generated by Django 5.0.6 on 2024-08-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
