# Generated by Django 5.0.6 on 2024-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe')], max_length=2)),
                ('moderator', models.BooleanField()),
            ],
        ),
    ]
